services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  db:
    image: postgres:16-alpine
    container_name: db
    hostname: db
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    hostname: app
    volumes:
      - ./data/logs:/app/logs
    depends_on:
      - db
    entrypoint: ["sh", "-c", "alembic upgrade head && exec python main.py"]

volumes:
  data:
